# Configuration file for Azure IoT device connection and application parameters

connection_string: "HostName=msy-iot-ta-prod.azure-devices.net;DeviceId=site-001-iot;SharedAccessKey=/NgOhSuu/DSm9SSAxeg5vkuirvAe+aTlufTRrg/OYKY="
device_id: "site-001-iot"
search_for_slave_ip_address: false
slave_ip_address: "192.168.68.100"
detect_power: True