# Configuration file for Azure IoT device connection and application parameters

connection_string: "HostName=msy-iot-ta-prod.azure-devices.net;DeviceId=site-001-iot;SharedAccessKey=/NgOhSuu/DSm9SSAxeg5vkuirvAe+aTlufTRrg/OYKY="

id_scope: "0ne011AC31E"
device_id: "site-001-iot"
symmetric_key: "/NgOhSuu/DSm9SSAxeg5vkuirvAe+aTlufTRrg/OYKY="
#"XmTtnVUI9USMrb8KPyFJnNI33tXQSQN+ELLlCUGY28BUmZXTJ+VfD3Q+OaSbSNB8v9XiY6zrR17RAIoT5lR3vA=="
provisioning_host: "msy-iot-ta-prod.azure-devices.net"
#"global.azure-devices-provisioning.net"

heartbeat_interval_sec: 30.0 # seconds

log_dir: "logs"  # Directory to store log files
print_level: "INFO"  # Minimum level for terminal printing: "DEBUG", "INFO", "WARN", "ERROR"
log_level: "DEBUG"  # Minimum level for file logging: "DEBUG", "INFO", "WARN", "ERROR"

relay_gpio_line: 17  # GPIO line number for relay control
power_on_delay_sec: 5.0  # Delay after powering on the slave
search_for_slave_ip_address: false
slave_ip_address: ""
