# Configuration file for Azure IoT device connection and application parameters

id_scope: "0ne01173A60"
device_id: "site-001-iot"
symmetric_key: "8SLw+5EYL2ZJ9jRagD7dMgQOb806nS3yQK4GgR4wTpGyAtR18LQRCBQSANdllSTb04Tlck8WiBN6AIoTsLefpQ=="
provisioning_host: "global.azure-devices-provisioning.net"

heartbeat_interval_sec: 30.0 # seconds

log_dir: "logs"  # Directory to store log files
print_level: "INFO"  # Minimum level for terminal printing: "DEBUG", "INFO", "WARN", "ERROR"
log_level: "DEBUG"  # Minimum level for file logging: "DEBUG", "INFO", "WARN", "ERROR"

relay_gpio_line: 17  # GPIO line number for relay control
power_on_delay_sec: 5.0  # Delay after powering on the slave
search_for_slave_ip_address: false
slave_ip_address: ""